# Generated by Django 6.1.2 on 2026-10-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('CHEQUING', 'Chequing'), ('SAVINGS', 'Savings')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed'), ('DORMANT', 'Dormant')], max_length=16)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='CAD', max_length=8)),
                ('opened_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('ACCOUNT', 'Account'), ('TRANSACTION', 'Transaction')], max_length=16)),
                ('payload', models.JSONField()),
                ('reasons', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('source', models.CharField(choices=[('API', 'Api'), ('CSV_IMPORT', 'Csv Import')], default='API', max_length=16)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('PURCHASE', 'Purchase'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit'), ('REVERSAL', 'Reversal')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('channel', models.CharField(choices=[('ONLINE', 'Online'), ('POS', 'Pos'), ('ATM', 'Atm'), ('PARTNER_FI', 'Partner Fi')], max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='banking.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='banking.account')),
            ],
        ),
    ]
